name: Build and Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CastLabs EVS
        run: pip install castlabs_evs

      - name: Install dependencies
        run: npm install

      - name: Download Electron Binary
        run: node node_modules/electron/install.js

      - name: Build Webpack
        run: npm run build

      - name: Package with electron-builder
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Crunchyroll-Desktop-App-Installer
          path: release/*.exe
